# Azure DevOps Pipeline for Reservation Management Feature

trigger:
  branches:
    include:
      - main

variables:
  # Node.js version for frontend
  nodeVersion: '18.x'
  # Java version for backend
  javaVersion: '17'

stages:
# =============================================================================
# CONTINUOUS INTEGRATION STAGE
# =============================================================================
- stage: CI
  displayName: 'Continuous Integration for Reservation Management'
  jobs:

  # Build Frontend Reservation Management Feature
  - job: BuildFrontendReservationManagement
    displayName: 'Build Frontend Reservation Management Feature'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    # Setup Node.js Environment
    - task: NodeTool@0
      displayName: 'Setup Node.js $(nodeVersion)'
      inputs:
        versionSpec: '$(nodeVersion)'

    # Clean and Install Dependencies
    - script: |
        cd frontend
        rm -rf node_modules package-lock.json
        npm install
      displayName: 'Clean and Install Frontend Dependencies'

    # Install Rollup (Explicitly)
    - script: |
        cd frontend
        npm install rollup
      displayName: 'Install Rollup'

    # Log Installed Dependencies
    - script: |
        cd frontend
        npm list --depth=0
      displayName: 'Log Installed Dependencies'

    # Build Frontend
    - script: |
        cd frontend
        npm run build
      displayName: 'Build Frontend Reservation Management Feature'

    # Publish Build Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Frontend Build Artifacts'
      inputs:
        pathToPublish: 'frontend/dist'
        artifactName: 'le-restaurant-frontend'
        publishLocation: 'Container'