# Azure DevOps Pipeline for Reservation Management Feature

trigger:
  branches:
    include:
      - main

variables:
  # Node.js version for frontend
  nodeVersion: '20.x'
  # Java version for backend
  javaVersion: '17'

stages:
# =============================================================================
# CONTINUOUS INTEGRATION STAGE
# =============================================================================
- stage: CI
  displayName: 'Continuous Integration for Reservation Management'
  jobs:

  # Backend Tests for Reservation Management
  - job: TestBackendReservationManagement
    displayName: 'Test Backend Reservation Management Feature'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    # Setup JDK
    - task: JavaToolInstaller@1
      displayName: 'Set up JDK $(javaVersion)'
      inputs:
        version: '$(javaVersion)'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    # Cache Gradle Dependencies
    - task: Cache@2
      displayName: 'Cache Gradle Dependencies'
      inputs:
        key: 'gradle | "$(Agent.OS)" | backend/gradle/wrapper/gradle-wrapper.properties'
        restoreKeys: |
          gradle | "$(Agent.OS)"
          gradle
        path: '~/.gradle'

    # Run Backend Tests
    - script: |
        cd backend
        chmod +x gradlew # Ensure gradlew is executable
        ./gradlew test --tests "com.lerestaurant.le_restaurant_backend.service.ReservationServiceTest" --stacktrace --info
      displayName: 'Run Backend Reservation Management Tests'

    # Publish Test Results
    - task: PublishTestResults@2
      displayName: 'Publish Backend Test Results'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/build/test-results/test/*.xml'
        failTaskOnFailedTests: true

  # Frontend Tests for Reservation Management
  - job: TestFrontendReservationManagement
    displayName: 'Test Frontend Reservation Management Feature'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    # Setup Node.js Environment
    - task: NodeTool@0
      displayName: 'Setup Node.js $(nodeVersion)'
      inputs:
        versionSpec: '$(nodeVersion)'

    # Cache Node Modules
    - task: Cache@2
      displayName: 'Cache Node Modules'
      inputs:
        key: 'npm | "$(Agent.OS)" | frontend/package-lock.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
          npm
        path: 'frontend/node_modules'

    # Install Dependencies
    - script: |
        cd frontend
        npm install
      displayName: 'Install Frontend Dependencies'

    # Run Frontend Tests
    - script: |
        cd frontend
        npm test -- ReservationForm.test.tsx
      displayName: 'Run Frontend Reservation Management Tests'

    # Publish Test Results
    - task: PublishTestResults@2
      displayName: 'Publish Frontend Test Results'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results/*.xml'
        failTaskOnFailedTests: true