spring.datasource.url=jdbc:postgresql://postgres:5432/lerestaurant
spring.datasource.username=${POSTGRES_USER:lerestaurant}
spring.datasource.password=${POSTGRES_PASSWORD:lerestaurant}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
