-- Initial data for Le Restaurant (F108)
-- This file is automatically executed by Spring Boot on startup

-- Insert test users (password for all users is "password123")
-- BCrypt hash: $2a$10$N9qo8uLOickgx2ZMRZoMye/0cQs4z0b4LT.pZ2VZZQPy0sFpMAF5C
INSERT INTO users (email, password_hash, first_name, last_name, phone_number, user_role, status, created_at) VALUES
('customer@lerestaurant.com', '$2a$10$N9qo8uLOickgx2ZMRZoMye/0cQs4z0b4LT.pZ2VZZQPy0sFpMAF5C', 'John', 'Customer', '0412345678', 'CUSTOMER', 'ACTIVE', CURRENT_TIMESTAMP),
('manager@lerestaurant.com', '$2a$10$N9qo8uLOickgx2ZMRZoMye/0cQs4z0b4LT.pZ2VZZQPy0sFpMAF5C', 'Jane', 'Manager', '0423456789', 'MANAGER', 'ACTIVE', CURRENT_TIMESTAMP),
('admin@lerestaurant.com', '$2a$10$N9qo8uLOickgx2ZMRZoMye/0cQs4z0b4LT.pZ2VZZQPy0sFpMAF5C', 'Admin', 'User', '0434567890', 'ADMIN', 'ACTIVE', CURRENT_TIMESTAMP);

-- Insert restaurant tables (created_at is required for all records)
INSERT INTO restaurant_tables (table_number, capacity, table_type, status, location_description, created_at) VALUES
('A1', 2, 'REGULAR', 'AVAILABLE', 'Window side, romantic setting', CURRENT_TIMESTAMP),
('A2', 2, 'REGULAR', 'AVAILABLE', 'Window side', CURRENT_TIMESTAMP),
('A3', 2, 'BOOTH', 'AVAILABLE', 'Cozy corner booth', CURRENT_TIMESTAMP),
('B1', 4, 'REGULAR', 'AVAILABLE', 'Center area', CURRENT_TIMESTAMP),
('B2', 4, 'REGULAR', 'AVAILABLE', 'Center area', CURRENT_TIMESTAMP),
('B3', 4, 'BOOTH', 'AVAILABLE', 'Private booth, family-friendly', CURRENT_TIMESTAMP),
('B4', 4, 'REGULAR', 'AVAILABLE', 'Near kitchen entrance', CURRENT_TIMESTAMP),
('C1', 6, 'REGULAR', 'AVAILABLE', 'Large table, center', CURRENT_TIMESTAMP),
('C2', 6, 'BOOTH', 'AVAILABLE', 'Private dining area', CURRENT_TIMESTAMP),
('D1', 8, 'REGULAR', 'AVAILABLE', 'Group table, perfect for celebrations', CURRENT_TIMESTAMP),
('D2', 8, 'REGULAR', 'AVAILABLE', 'Group table with view', CURRENT_TIMESTAMP),
('E1', 10, 'REGULAR', 'AVAILABLE', 'Large party table, can be split', CURRENT_TIMESTAMP);

-- Note: The table_id column is auto-generated by the database
